# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: true

reviews:
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: true

  instructions: |
    Please review this pull request and provide feedback on:
    - Code quality and best practices
    -industry standards compliance
    - Potential bugs or issues
    - Performance considerations
    - Security concerns
    - Test coverage and missing tests

    Always point out:
    - Unhandled error cases
    - Edge cases
    - Unsafe assumptions
    - Missing validations

    Be clear, direct, and constructive in your feedback.

  path_filters:
    - "!**/*.xml"

  auto_review:
    enabled: true
    drafts: true
    ignore_title_keywords:
      - "WIP"
    base_branches:
      - "main"
      - "develop"
      - "feature/*"

chat:
  auto_reply: true
